package model.dao;

/**
 * Exception class for errors in DAO layer
 * 
 * @author mr222xu
 *
 */
public class DAOException extends Exception {

	// Generated by Eclipse
	private static final long serialVersionUID = 4314845833827032852L;
	
	/**
	 * Constructor
	 * 
	 * @param t - A throwable object
	 */
	public DAOException(Throwable t) {
		super(t);
	}
}
