package model;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import model.dao.DAOException;
import model.dao.MemberDAO;
import model.dao.impl.MemberDAOImpl;

/**
 * Member class
 * 
 * @author mr222xu
 *
 */
public class Member implements Comparable<Member> {
	
	// Members
	private String firstname;
	private String lastname;
	private PersonalNumber personalNumber;
	private Set<Boat> boats;
	private int id;
	
	// Static member
	private final static MemberDAO DAO = new MemberDAOImpl();

	/**
	 * Constructor
	 * 
	 * @param firstname - The member's first name
	 * @param lastname - The member's last name
	 * @param personalNumber - The member's personal number
	 */
	public Member(String firstname, String lastname, PersonalNumber personalNumber) {
		setFirstname(firstname);
		setLastname(lastname);
		setPersonalNumber(personalNumber);
		setBoats(new HashSet<Boat>());
		
		// Handle failure in MemberDAO
		try {
			setId(DAO.getNextId());
		} catch (DAOException e) {
			// Default to one
			setId(1);
		}
	}
	
	/**
	 * Private constructor when using the Builder
	 *
	 * @param builder - A Member Builder object
	 */
	private Member(Builder builder) {
		setFirstname(builder.firstname);
		setLastname(builder.lastname);
		setPersonalNumber(builder.personalNumber);
		setBoats(builder.boats);
		setId(builder.id);
	}

	/**
	 * To get the member's first name
	 * 
	 * @return - A String object representing the member's first name
	 */
	public String getFirstname() {
		return firstname;
	}

	/**
	 * To set the member's first name
	 * 
	 * @param firstname - The member's first name
	 */
	public void setFirstname(String firstname) {
		if (firstname == null)
			throw new IllegalArgumentException("Member firstname cannot be null.");
			
		this.firstname = firstname;
	}

	/**
	 * To get the member's last name
	 * 
	 * @return - A String object representing the member's last name
	 */
	public String getLastname() {
		return lastname;
	}

	/**
	 * To set the member's last name
	 * 
	 * @param firstname - The member's last name
	 */
	public void setLastname(String lastname) {
		if (lastname == null)
			throw new IllegalArgumentException("Member lastname cannot be null.");
		
		this.lastname = lastname;
	}
	
	/**
	 * To get the member's full name
	 * 
	 * @return - A String object representing the member's full name, i.e. first name and last name
	 */
	public String getName() {
		return firstname + " " + lastname;
	}

	/**
	 * To get the member's personal number
	 * 
	 * @return - A PersonalNumber object representing the member's personal number
	 */
	public PersonalNumber getPersonalNumber() {
		return personalNumber;
	}

	/**
	 * To set the member's personal number
	 * 
	 * @param personalNumber - The member's personal number
	 */
	public void setPersonalNumber(PersonalNumber personalNumber) {
		if (personalNumber == null)
			throw new IllegalArgumentException("Member personal number cannot be null.");
		
		this.personalNumber = personalNumber;
	}
	
	/**
	 * To add a boat to the member
	 * 
	 * @param boat - a boat object
	 */
	public void addBoat(Boat boat) {
		boats.add(boat);
	}
	
	/**
	 * Private method to set all boats for a member, used by the Member Builder
	 * 
	 * @param boats - a set of boat objects
	 */
	private void setBoats(Set<Boat> boats) {
		if (boats == null)
			boats = new HashSet<>();
		
		this.boats = boats;
	}
	
	/**
	 * To remove a boat from the member
	 * 
	 * @param boat - a boat object
	 */
	public void removeBoat(Boat boat) {
		boats.remove(boat);
	}
	
	/**
	 * To get a list of all of the member's boats
	 * 
	 * @return - a list of of all of the member's boats
	 */
	public List<Boat> getBoats() {
		List<Boat> list = new ArrayList<Boat>();
		list.addAll(boats);

		return Collections.unmodifiableList(list);
	}
	
	/**
	 * To get the number of boats that is registered to the member
	 * 
	 * @return - number of boats as an integer
	 */
	public int getNumberOfBoats() {
		return boats.size();
	}
	
	/**
	 * Private method to set the member ID. Used by the Member Builder
	 * 
	 * @param id - a member ID
	 */
	private void setId(int id) {
		if (id < 0)
			throw new IllegalArgumentException("Member id cannot be less than 1.");
		
		this.id = id;
	}

	/**
	 * To get the member's ID
	 * 
	 * @return - member ID
	 */
	public int getId() {
		return id;
	}
	
	@Override
	public int compareTo(Member other) {
		return Integer.compare(id, other.id);
	}
	
	// Generated by Eclipse
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((boats == null) ? 0 : boats.hashCode());
		result = prime * result + ((firstname == null) ? 0 : firstname.hashCode());
		result = prime * result + id;
		result = prime * result + ((lastname == null) ? 0 : lastname.hashCode());
		result = prime * result + ((personalNumber == null) ? 0 : personalNumber.hashCode());
		return result;
	}

	// Generated by Eclipse
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Member other = (Member) obj;
		if (boats == null) {
			if (other.boats != null)
				return false;
		} else if (!boats.equals(other.boats))
			return false;
		if (firstname == null) {
			if (other.firstname != null)
				return false;
		} else if (!firstname.equals(other.firstname))
			return false;
		if (id != other.id)
			return false;
		if (lastname == null) {
			if (other.lastname != null)
				return false;
		} else if (!lastname.equals(other.lastname))
			return false;
		if (personalNumber == null) {
			if (other.personalNumber != null)
				return false;
		} else if (!personalNumber.equals(other.personalNumber))
			return false;
		return true;
	}

	/**
	 * Builder pattern
	 * 
	 * @author mr222xu
	 *
	 */
	public static class Builder {
		private String firstname;
		private String lastname;
		private PersonalNumber personalNumber;
		private Set<Boat> boats;
		private int id;
		
		public Builder() {
			// Empty Builder constructor
		}
		
		public Builder firstname(String firstname) {
			this.firstname = firstname;
			return this;
		}
		
		public Builder lastname(String lastname) {
			this.lastname = lastname;
			return this;
		}
		
		public Builder personalNumber(PersonalNumber personalNumber) {
			this.personalNumber = personalNumber;
			return this;
		}
		
		public Builder boats(Set<Boat> boats) {
			this.boats = boats;
			return this;
		}
		
		public Builder id(int id) {
			this.id = id;
			return this;
		}
		
		public Member build() {
			return new Member(this);
		}
	}
}
