package model;

import java.time.LocalDate;
import java.time.Period;
import java.time.Year;
import java.time.chrono.IsoChronology;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeFormatterBuilder;
import java.time.format.DateTimeParseException;
import java.time.format.ResolverStyle;
import java.time.temporal.ChronoField;
import java.util.regex.Pattern;

/**
 * Personal number class
 * 
 * @author mr222xu
 *
 */
public class PersonalNumber {

	// Members
	private LocalDate date;
	private String lastFour;
	
	// Static members
	// See https://docs.oracle.com/javase/8/docs/api/java/util/regex/Pattern.html for Java regular expressions
	private final static Pattern PERS_NUM_PATTERN = Pattern.compile("^\\d{6}-\\d{4}$");
	// To handle e.g. 850101 as 19850101 and not 20850101
	private final static DateTimeFormatter DATE_FORMAT = new DateTimeFormatterBuilder()
			.parseCaseInsensitive()
			.appendValueReduced(ChronoField.YEAR, 2, 2, Year.now().getValue() - 99)
            .appendValue(ChronoField.MONTH_OF_YEAR, 2)
            .appendValue(ChronoField.DAY_OF_MONTH, 2)
            .optionalStart()
            .toFormatter()
            .withResolverStyle(ResolverStyle.STRICT)
            .withChronology(IsoChronology.INSTANCE);
	
	/**
	 * Constructor
	 * 
	 * @param personalNumber a personal number as a String object in format YYMMDD-XXXX
	 * @throws IllegalArgumentException if argument doesn't adhere to format YYMMDD-XXXX
	 */
	public PersonalNumber(String personalNumber) {
		setPersonalNumber(personalNumber);
	}

	/**
	 * Set personal number
	 * 
	 * @param personalNumber a personal number as a String object in format YYMMDD-XXXX
	 * @throws IllegalArgumentException if argument doesn't adhere to format YYMMDD-XXXX
	 */
	public void setPersonalNumber(String personalNumber) {	    
	    // Validate format
	    if (!PERS_NUM_PATTERN.matcher(personalNumber).matches())
	    	throw new IllegalArgumentException("Personal number is not on format YYMMDD-XXXX.");
	    
		// Split the string
	    String[] split = personalNumber.split("-");
	    
	    // Parse last four
	    lastFour = split[1];
		
	    // Parse date
		try {
		    date = LocalDate.parse(split[0], DATE_FORMAT);
		} catch (DateTimeParseException e) {
			throw new IllegalArgumentException("Date of personal number is not valid. ");
		}
		
		// Check if future
		if (date.isAfter(LocalDate.now()))
			throw new IllegalArgumentException("Date of personal number is in the future.");
	}
	
	/**
	 * Get date in personal number
	 * 
	 * @return a LocalDate object
	 */
	public LocalDate getDate() {
		return date;
	}
	
	/**
	 * Get last four digits in personal number
	 * 
	 * @return a String object
	 */
	public String getLastFourDigits() {
		return lastFour;
	}
	
	/**
	 * Return age of person
	 * 
	 * @return age as an integer
	 */
	public int getAge() {
		return Period.between(date, LocalDate.now()).getYears();
	}
	
	// Generated by Eclipse
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((date == null) ? 0 : date.hashCode());
		result = prime * result + ((lastFour == null) ? 0 : lastFour.hashCode());
		return result;
	}

	// Generate by Eclipse
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		PersonalNumber other = (PersonalNumber) obj;
		if (date == null) {
			if (other.date != null)
				return false;
		} else if (!date.equals(other.date))
			return false;
		if (lastFour == null) {
			if (other.lastFour != null)
				return false;
		} else if (!lastFour.equals(other.lastFour))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return new StringBuilder(date.format(DATE_FORMAT))
					.append("-")
					.append(lastFour)
					.toString();
	}
}
